import { Product } from '@/types'

export const products: Product[] = [
  {
    id: '1',
    slug: 'ira-cola-super',
    name: 'IRA Cola Super',
    tagline: 'Bold. Dark. Unstoppable.',
    description: 'The cola that hits different. Rich carbonation, deep cola character, zero compromise.',
    longDescription: 'Experience the ultimate cola rush with IRA Cola Super. Crafted with premium ingredients to deliver a bold, authentic taste that awakens your senses.',
    flavourNotes: ['Deep Cola', 'Caramel Undertone', 'Strong Fizz'],
    ingredients: ['Carbonated Water', 'Sugar', 'Natural Cola Flavour', 'Citric Acid', 'Caramel Colour'],
    volume: '250ml',
    mrp: 10,
    color: { primary: '#3D1A0A', secondary: '#7B3A1E', text: '#F5F0E8' },
    image: '/images/products/cola.png',
    badge: 'Bestseller',
    available: true,
  },
  {
    id: '2',
    slug: 'ira-string',
    name: 'IRA String',
    tagline: 'Sharp. Fiery. Alive.',
    description: 'A bold ginger-spice soda that wakes you up. Not for the faint-hearted.',
    longDescription: 'For those who crave a kick. IRA String brings a fiery blend of ginger and spices, delivering a sharp and enlivening soda experience.',
    flavourNotes: ['Ginger Bite', 'Spice Kick', 'Warming Finish'],
    ingredients: ['Carbonated Water', 'Sugar', 'Natural Ginger Extract', 'Citric Acid', 'Spice Blend'],
    volume: '250ml',
    mrp: 10,
    color: { primary: '#FF4500', secondary: '#FF7433', text: '#0A0A0A' },
    image: '/images/products/string.png',
    badge: 'Fan Favourite',
    available: true,
  },
  {
    id: '3',
    slug: 'ira-blueberry',
    name: 'IRA Blueberry',
    tagline: 'Wild. Purple. Electric.',
    description: 'Bursting with real blueberry character. Bold fizz meets berry bliss.',
    longDescription: 'Our blueberry soda is a vibrant explosion of wild berry flavour. Perfectly balanced with a crisp finish, it is the electric refreshment you need.',
    flavourNotes: ['Wild Blueberry', 'Light Floral', 'Crisp Finish'],
    ingredients: ['Carbonated Water', 'Sugar', 'Natural Blueberry Flavour', 'Citric Acid', 'Colour (Anthocyanin)'],
    volume: '250ml',
    mrp: 10,
    color: { primary: '#2D0A4E', secondary: '#5B1E8A', text: '#F5F0E8' },
    image: '/images/products/blueberry.png',
    available: true,
  },
  {
    id: '4',
    slug: 'ira-lime-lemon',
    name: 'IRA Lime Lemon',
    tagline: 'Sharp. Fresh. Essential.',
    description: 'Classic lime-lemon with a character of its own. Pure refreshment, amplified.',
    longDescription: 'The ultimate thirst quencher. Our Lime Lemon soda combines zesty lime and bright lemon to deliver pure, unadulterated refreshment.',
    flavourNotes: ['Zesty Lime', 'Bright Lemon', 'Clean Finish'],
    ingredients: ['Carbonated Water', 'Sugar', 'Natural Lime & Lemon Flavour', 'Citric Acid'],
    volume: '250ml',
    mrp: 10,
    color: { primary: '#1A5C1A', secondary: '#2E8B2E', text: '#F5F0E8' },
    image: '/images/products/lime%20lemon.png',
    available: true,
  },
  {
    id: '5',
    slug: 'ira-lemon-salt',
    name: 'IRA Lemon Salt',
    tagline: 'Tangy. Salty. Perfect.',
    description: 'A traditional twist on refreshment with a perfect balance of salt and tangy lemon.',
    longDescription: 'Inspired by local street coolers, IRA Lemon Salt gives you that instant rehydration hit with a sharp salty edge.',
    flavourNotes: ['Tangy Lemon', 'Salty Edge', 'Thirst Quenching'],
    ingredients: ['Carbonated Water', 'Sugar', 'Natural Lemon Extract', 'Salt', 'Citric Acid'],
    volume: '250ml',
    mrp: 10,
    color: { primary: '#E5D624', secondary: '#E5D624', text: '#0A0A0A' },
    image: '/images/products/lime%20salt.png',
    available: true,
  },
  {
    id: '6',
    slug: 'ira-orange',
    name: 'IRA Orange',
    tagline: 'Bright. Citrusy. Joyful.',
    description: 'Pure sunshine in a bottle. A burst of sweet and tangy orange flavour.',
    longDescription: 'Sweet, bright, and bursting with real orange character. IRA Orange is the joyful, nostalgic taste you love, upgraded with premium fizz.',
    flavourNotes: ['Sweet Orange', 'Citrus Burst', 'Smooth Finish'],
    ingredients: ['Carbonated Water', 'Sugar', 'Natural Orange Flavour', 'Citric Acid', 'Colour'],
    volume: '250ml',
    mrp: 10,
    color: { primary: '#FF7B00', secondary: '#FF8C00', text: '#F5F0E8' },
    image: '/images/products/orange2.png',
    available: true,
  },
  {
    id: '7',
    slug: 'ira-clubsoda',
    name: 'IRA Clubsoda',
    tagline: 'Crisp. Clear. Versatile.',
    description: 'The ultimate mixer. Ultra-purified water with bold, biting carbonation.',
    longDescription: 'Crafted for the perfect mix or straight refreshment. Our Clubsoda offers aggressive carbonation and pure, clean taste.',
    flavourNotes: ['Biting Fizz', 'Pure Water', 'Clean Palette'],
    ingredients: ['Carbonated Water', 'Mineral Salts'],
    volume: '250ml',
    mrp: 10,
    color: { primary: '#0A4A8E', secondary: '#1A6BBE', text: '#F5F0E8' },
    image: '/images/products/club%20soda.png',
    available: true,
  },
  {
    id: '8',
    slug: 'ira-water-bottle',
    name: 'IRA Water Bottle',
    tagline: 'Pure. Essential. Hydration.',
    description: 'Packaged drinking water, purified to perfection for everyday hydration.',
    longDescription: 'Crystal clear, thoroughly purified drinking water. Essential hydration you can trust from IRA Beverages.',
    flavourNotes: ['Pure', 'Crisp', 'Refreshing'],
    ingredients: ['Purified Water'],
    volume: '500ml',
    mrp: 10,
    color: { primary: '#4A90E2', secondary: '#5AA0F2', text: '#F5F0E8' },
    image: '/images/products/water%20bottle.png',
    available: true,
  }
]
